=== Kostyansa/TelegramAdapter/schemas/response.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Platform Integration Scheme, version 0.1, create date 27.04.2021 -->
<xs:schema xmlns="temporary-schema-name"  xmlns:xs="http://www.w3.org/2001/XMLSchema"  elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:complexType name="responsetype">
        <xs:sequence>
            <xs:element name="text" type="xs:stringtype" minOccurs=0>
            <xs:element name="location" type="locationtype" minOccurs=0>
            <xs:element name="keyboard" type="keyboardtype" minOccurs=0>
            <xs:element name="picture" type="picturetype" minOccurs=0>
        </xs:sequence>
        <xs:attribute name="name" type="xs:stringtype"/>
    </xs:complexType>
    <xs:complexType name="keyboardtype">
        <xs:sequence>
            <xs:element name="key" type="keytype" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:stringtype"/>
        <xs:attribute name="row_width" type="xs:positiveInteger"/>
    <xs:complexType/>
    <xs:complexType name="keytype">
        <xs:sequence>
            <xs:element name="text" type="xs:stringtype"/>
            <xs:element name="callback_data" type="xs:stringtype" minOccurs=0>
            <xs:element name="URL" type="xs:stringtype" minOccurs=0>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="picturetype">
        <xs:sequence>
            <xs:element name="URL" type="xs:stringtype" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="locationtype">
        <xs:sequence>
            <xs:element name="latitude" type="xs:decimal"/>
            <xs:element name="longitude" type="xs:decimal"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="response" type="responsetype"/>
</xs:schema>

=== Kostyansa/TelegramAdapter/schemas/examples/information.xml
<?xml version="1.0" encoding="UTF-8"?>

<response
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="../response.xsd">
    <name>–ò–Ω—Ñ–æ—Ä–º–∞—Ü–∏—è</name>
    <keyboard row_width=2>
        <key>
            <text>‚è∞ –†–∞—Å–ø–∏—Å–∞–Ω–∏–µ –∑–≤–æ–Ω–∫–æ–≤</text>
            <callback_data>‚è∞ –†–∞—Å–ø–∏—Å–∞–Ω–∏–µ –∑–≤–æ–Ω–∫–æ–≤</callback_data>
        </key>
        <key>
            <text>üéì –ö–æ—Ä–æ—Ç–∫–æ –æ–± —É—á–µ–±–µ</text>
            <callback_data>üéì –ö–æ—Ä–æ—Ç–∫–æ –æ–± —É—á–µ–±–µ</callback_data>
        </key>
    </keyboard>
</response>
